### ISSUE TITLE
Instalation fail

### ISSUE THREAD

**Issue by Hoinkas** [Kuncheria-Kuruvilla/code-aesthetics#1]
Hi!

I wanted to see that presentation and cloned it locally, installed dependencies and tried to run via npm start.

That's where I got this error:

```
 PS C:\Development\code-aesthetics> npm start

> code_aesthetics@1.0.0 start
> mdx-deck deck.mdx

info Deleting .cache, public
info Successfully deleted directories

 ERROR 

(node:61324) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Development\code-aesthetics\node_modules\@gatsbyjs\relay-compiler\package.json' of 'RelayCompilerPublic'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

success open and validate gatsby-configs - 0.110 s
success load plugins - 0.530 s
success onPreInit - 0.071 s
success initialize cache - 0.073 s
success copy gatsby files - 0.190 s
success onPreBootstrap - 0.073 s
warn Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
success source and transform nodes - 0.974 s
success Add explicit types - 0.073 s
success Add inferred types - 0.129 s
success Processing types - 0.109 s
success building schema - 0.429 s
success createPages - 0.293 s
success createPagesStatefully - 0.110 s
success onPreExtractQueries - 0.068 s
success update schema - 0.084 s
success extract queries from components - 0.217 s
success write out requires - 0.109 s
success write out redirect data - 0.080 s
success onPostBootstrap - 0.080 s
⠀                                                                                                                                                       
info bootstrap finished - 6.603 s
⠀
success run static queries - 0.070 s
success run page queries - 0.108 s — 3/3 77.22 queries/second

 ERROR 

UNHANDLED REJECTION error:0308010C:digital envelope routines::unsupported



  Error: error:0308010C:digital envelope routines::unsupported

  - hash:69 new Hash
    node:internal/crypto/hash:69:19

  - node:crypto:133 Object.createHash
    node:crypto:133:10

  - createHash.js:135 module.exports
    [code-aesthetics]/[webpack]/lib/util/createHash.js:135:53

  - NormalModule.js:417 NormalModule._initBuildHash
    [code-aesthetics]/[webpack]/lib/NormalModule.js:417:16

  - NormalModule.js:452
    [code-aesthetics]/[webpack]/lib/NormalModule.js:452:10

  - NormalModule.js:323
    [code-aesthetics]/[webpack]/lib/NormalModule.js:323:13

  - LoaderRunner.js:367
    [code-aesthetics]/[loader-runner]/lib/LoaderRunner.js:367:11

  - LoaderRunner.js:233
    [code-aesthetics]/[loader-runner]/lib/LoaderRunner.js:233:18

  - LoaderRunner.js:111 context.callback
    [code-aesthetics]/[loader-runner]/lib/LoaderRunner.js:111:13

  - index.js:55
    [code-aesthetics]/[babel-loader]/lib/index.js:55:103


⠙ start webpack server
Error: Command failed with exit code 1 (Unknown system error -1): gatsby develop --host localhost --port 8000 --open
    at makeError (C:\Development\code-aesthetics\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Development\code-aesthetics\node_modules\execa\index.js:112:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

What should I do to be able to run presentation? Thanks!

**Comment by Kuncheria-Kuruvilla** [comment]
@Hoinkas Thanks a lot for reaching out. 

It looks like it works on node version `16.16.0`. For the time being you could use a node version manager like `nvm` to switch to this particular version. (using the command `nvm use 16.16.0`). 

Or you can also see the presentation hosted [here](https://code-aesthetics.netlify.app).

From what I learned so far, the error occurs when you try to use a cryptographic algorithm that is not supported by the version of OpenSSL installed on your system. 

I will look more deeper into the actual root cause and resolve the problem as soon as possible.

**Comment by Hoinkas** [comment]
@Kuncheria-Kuruvilla Thanks for response!

I just wanted to see presentation and was able to thanks to your link.
If that repo is your "private" project and I found it by accident - you don't want to change code so some people wouldn't have problems with running it locally - then feel free to close the issue and to forget about my question!

Have a good day!
